### ISSUE TITLE
Rollup error

### ISSUE THREAD

**Issue by AlexTNAC** [handsontable/angular-handsontable#16]
### Description
After following the instructions in https://handsontable.github.io/angular-handsontable/quick-start, I build my app with AOT, which is successful. Next I want to bundle everything in order to get a bundle.js file that I can import in my index.html (just as described here: https://angular.io/guide/aot-compiler#run-rollup in the Angular Docs). When I execute the rollup command I get

> Error: 'default' is not exported by node_modules\handsontable\es\index.js
> s://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
> _modules\angular-handsontable\src\hot-table.component.js (11:7)
> };
> import { Component, ElementRef, EventEmitter, Input, NgZone, Output, ViewEncapsulation, } from '@angular/core';
> import Handsontable from 'handsontable';
>        ^
> import { HotRegisterer } from './hot-registerer.service';
> import { HotHelper } from './hot-settings.utils';

As someone suggested I also tried modifying tsconfig.json as described here: https://handsontable.github.io/angular-handsontable/use-with-pro, but without the pro-suffix. This leads to the same error. How can I bundle my app when it contains the new Angular2 wrapper?

**Comment by swistach** [comment]
Hi @AlexTNAC,
In the latest version of the Handsontable this issue should be resolved.

**Comment by swistach** [comment]
New version is released. Could you check this out with the latest `angular-handsontable`(1.0.0-beta2)?

**Comment by AlexTNAC** [comment]
I just checked it out and it worked for the error mentioned above. But now I run into another (similar) error within another class:

> Error: 'default' is not exported by node_modules\handsontable\es\plugins\customBorders\customBorders.js
> s://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
> _modules\handsontable\es\plugins\index.js (8:7)
> import ContextMenu from './contextMenu/contextMenu';
> import CopyPaste from './copyPaste/copyPaste';
> import CustomBorders from './customBorders/customBorders';
>        ^
> import DragToScroll from './dragToScroll/dragToScroll';
> import ManualColumnFreeze from './manualColumnFreeze/manualColumnFreeze';

It seems that whenever you import something in your code that is not written inside the brackets {}, that it can't be resolved during rollup.

**Comment by AlexTNAC** [comment]
Hi @swistach , we are still running into this issue. The release of beta 3 didn't solve it for us. This slows down our development process, could you please take a look at it? Thank you very much!

**Comment by swistach** [comment]
Hi @AlexTNAC,
Sorry for my late reply. Currently, I'm working on scroll improvement and I can't back to angular-handsontable. I'll back to this wrapper as soon as possible, to resolve issues related to `zone.js` and `rollup`.
All I can do now is apologize for this inconvenience.

**Comment by AlexTNAC** [comment]
Hi @swistach ,

no problem and thanks for your reply! Looking forward to get a fix from you sometime.

Alex

**Comment by swistach** [comment]
Hi @AlexTNAC, could you check `--aot` but using `zone.js@0.8.19`?
(Additionally, you have to remove changes in `polyfills.ts`)

**Comment by swistach** [comment]
I suppose that rollup works with suggested instructions. So, now I close this issue, but you can reopen it if you still have problems related to `zone.js`.
